"""2

Revision ID: e27bdf2836bc
Revises: 366f6fd78554
Create Date: 2025-03-18 07:05:35.438333

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e27bdf2836bc"
down_revision: Union[str, None] = "366f6fd78554"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taken_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("strategy_name", sa.String(), nullable=True),
        sa.Column("entry_timestamp", sa.DateTime(), nullable=True),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("prev_day_high", sa.Float(), nullable=True),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.Column("shares", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("position_size_percentage", sa.Float(), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=True),
        sa.Column("exit_timestamp", sa.DateTime(), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("profit_loss", sa.Float(), nullable=True),
        sa.Column("profit_loss_percentage", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_taken_trades_id"), "taken_trades", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_taken_trades_id"), table_name="taken_trades")
    op.drop_table("taken_trades")
    # ### end Alembic commands ###
